project_id = "dsylclbnkddaghmsptax"

[functions.smoobu-booking]
verify_jwt = false

[functions.fetch-smoobu-prices]
verify_jwt = false

[functions.fetch-google-reviews]
verify_jwt = false

[functions.find-place-id]
verify_jwt = false

[functions.fetch-facebook-reviews]
verify_jwt = false