// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsylclbnkddaghmsptax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzeWxjbGJua2RkYWdobXNwdGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDQ4MjAsImV4cCI6MjA3MjY4MDgyMH0.eAI40pPKxv2zYj6B5CGQsutsfrSYd5E8wD9d7JyCAE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});